### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by bamakant** [bamakant/HeyIndia#2]
Upload logo at this location @kindacoder 
https://github.com/HeyIndia/HeyIndia/tree/master/app/src/main/res/drawable

**Comment by kindacoder** [comment]
@bamakant  In which format ? And please update what you have done till now.

**Comment by bamakant** [comment]
Whatever formate you have, you can upload it, I will do the rest.
I am working and will update when a particular section will completed.

**Comment by kindacoder** [comment]
Don't you think we should change the name of the repo ? from **HeyIndia** to **HeyIndia Android App** ??

**Comment by bamakant** [comment]
I thought so, Will do it later, I need to check something before change the name of repo on Android Studio because It was created directly from Android Studio.

**Comment by bamakant** [comment]
App has been updated with new Logo.
