### ISSUE TITLE
Please upload app

### ISSUE THREAD

**Issue by kindacoder** [bamakant/HeyIndia#3]
Please upload the APK file every time you update the app, so that Contributors can download it and run it in their phone @bamakant

**Comment by bamakant** [comment]
APK has been updated already. Check it out. I can understand that's why I have released new APK each time I update the app.

**Comment by bamakant** [comment]
You can get the new APK each time at this location https://github.com/HeyIndia/HeyIndia/tree/master/app/release

**Comment by kindacoder** [comment]
> You can get the new APK each time at this location https://github.com/HeyIndia/HeyIndia/tree/master/app/release

cool :+1: Let me update this on `readme.md` .
